"""empty message

Revision ID: 749912b11aa0
Revises: a061dea0013a
Create Date: 2023-01-30 17:05:49.288907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749912b11aa0'
down_revision = 'a061dea0013a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone-medication',
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone-medication')
    # ### end Alembic commands ###
